# Default Image
image: quay.io/lifechurch/k8s-deploy-helper:3.0.0

variables:
  BINARY_NAME: $CI_PROJECT_NAME
  KUBE_DOMAIN: mydomain.com

.prep_go: &prep_go
  before_script:
    - export GL_URL=$(echo $CI_PROJECT_URL | awk -F/ '{print $3}')
    - export GO_PROJECT_PATH="$GOPATH/src/$GL_URL/$CI_PROJECT_NAMESPACE"
    - mkdir -p $GO_PROJECT_PATH
    - ln -s $(pwd) $GO_PROJECT_PATH
    - export GO_PROJECT_PATH="$GO_PROJECT_PATH/$CI_PROJECT_NAME"
    - cd $GO_PROJECT_PATH

stages:
  - build

go_build:
  <<: *prep_go
  stage: build
  image: golang:1.14
  script:
    - go get github.com/swaggo/swag/cmd/swag
    - make buildgo