language: go

env:
  global:
    - GO111MODULE=auto
    - GOBIN=/tmp
    - PATH=${GOBIN}:${PATH}

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - mkdir /tmp/src; ln -s ${PWD} /tmp/src
  - GOPATH=/tmp; cd ${GOPATH}/src/${PWD##*/}; make buildgo